version: "3.8"

services:
  mysql:
    image: mrki102/mysql-account-management
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - monitor_network
    volumes:
      - mysql-storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_USER=${MYSQL_USERNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
      - MYSQL_DATABASE=${MYSQL_DB_NAME}

  restservice:
    image: mrki102/restservice-account-management
    container_name: restservice
    restart: always
    ports:
      - "8080:8080"
    networks:
      - monitor_network
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PW}
    depends_on:
      - mysql

  cashdeposit:
    image: mrki102/cashdeposit-account-management
    container_name: cashdeposit
    restart: always
    ports:
      - "7070:7070"
    networks:
      - monitor_network
    volumes:
      - ${DEPOSIT_PROPERTIES_LOCATION}:/config/
    depends_on:
      - restservice

  cashtransaction:
    image: mrki102/cashtransaction-account-management
    container_name: cashtransaction
    restart: always
    ports:
      - "9090:9090"
    networks:
      - monitor_network
    volumes:
      - ${TRANSACTION_PROPERTIES_LOCATION}:/config/
    depends_on:
      - restservice

networks:
  monitor_network:

volumes:
  mysql-storage:
